//! Temporary storage of the most recent screenshots ("last N").
//!
//! Layout:
//! ```text
//! <root>/<id>/item.json         metadata (HistoryItem)
//! <root>/<id>/original.png      the raw capture (never modified)
//! <root>/<id>/image.png         the final image with annotations (only after editing)
//! <root>/<id>/thumb.png         small preview for the tray panel
//! <root>/<id>/annotations.json  editor document, lets you re-edit annotations later
//! ```
//! Items are pruned oldest-first when the limit is exceeded. Files saved by the user
//! ("Save" / "Save as") live elsewhere and are never touched.

use std::path::{Path, PathBuf};
use std::sync::Mutex;

use chrono::{DateTime, Local};
use serde::{Deserialize, Serialize};

use crate::settings::write_atomic;

#[derive(Debug, thiserror::Error)]
pub enum HistoryError {
    #[error("ошибка файловой системы: {0}")]
    Io(#[from] std::io::Error),
    #[error("снимок не найден: {0}")]
    NotFound(String),
    #[error("некорректный идентификатор снимка")]
    InvalidId,
    #[error("повреждённые метаданные: {0}")]
    Json(#[from] serde_json::Error),
}

pub type Result<T> = std::result::Result<T, HistoryError>;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HistoryFile {
    Original,
    Image,
    Thumb,
    Annotations,
    Meta,
}

impl HistoryFile {
    pub fn file_name(self) -> &'static str {
        match self {
            HistoryFile::Original => "original.png",
            HistoryFile::Image => "image.png",
            HistoryFile::Thumb => "thumb.png",
            HistoryFile::Annotations => "annotations.json",
            HistoryFile::Meta => "item.json",
        }
    }

    pub fn from_file_name(name: &str) -> Option<Self> {
        [Self::Original, Self::Image, Self::Thumb, Self::Annotations, Self::Meta]
            .into_iter()
            .find(|f| f.file_name() == name)
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HistoryItem {
    pub id: String,
    pub created_at: DateTime<Local>,
    pub width: u32,
    pub height: u32,
    /// "region" | "window" | "fullscreen" | "lastRegion" | "file" | "clipboard"
    pub source: String,
    /// Incremented on every change of the image; used for cache busting in the UI.
    #[serde(default)]
    pub revision: u32,
    #[serde(default)]
    pub edited: bool,
    #[serde(default)]
    pub box_file_id: Option<String>,
    /// Original Box shared link (`https://app.box.com/s/...`).
    #[serde(default)]
    pub box_url: Option<String>,
    /// Public link after rewriting (`https://advant.one/...`).
    #[serde(default)]
    pub share_url: Option<String>,
    /// Revision that was uploaded – when it differs from `revision` the link is outdated.
    #[serde(default)]
    pub uploaded_revision: Option<u32>,
    /// Last place the user saved the image to.
    #[serde(default)]
    pub saved_path: Option<String>,
}

pub struct HistoryStore {
    root: PathBuf,
    limit: Mutex<usize>,
}

impl HistoryStore {
    pub fn new(root: impl Into<PathBuf>, limit: usize) -> Result<Self> {
        let root = root.into();
        std::fs::create_dir_all(&root)?;
        Ok(Self { root, limit: Mutex::new(limit.max(1)) })
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    pub fn limit(&self) -> usize {
        *self.limit.lock().unwrap()
    }

    pub fn set_limit(&self, limit: usize) -> Result<()> {
        *self.limit.lock().unwrap() = limit.max(1);
        self.prune()
    }

    /// Ids are generated by us; anything else (e.g. `..`) is rejected so a crafted
    /// request to the image protocol can never escape the history folder.
    pub fn validate_id(id: &str) -> Result<()> {
        let ok = !id.is_empty() && id.len() <= 64 && id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-');
        if ok { Ok(()) } else { Err(HistoryError::InvalidId) }
    }

    pub fn dir(&self, id: &str) -> Result<PathBuf> {
        Self::validate_id(id)?;
        Ok(self.root.join(id))
    }

    pub fn path(&self, id: &str, file: HistoryFile) -> Result<PathBuf> {
        Ok(self.dir(id)?.join(file.file_name()))
    }

    /// Path of the current final image (edited one if it exists, otherwise the original).
    pub fn current_image_path(&self, id: &str) -> Result<PathBuf> {
        let edited = self.path(id, HistoryFile::Image)?;
        if edited.exists() {
            Ok(edited)
        } else {
            self.path(id, HistoryFile::Original)
        }
    }

    /// All items, newest first. Broken entries are skipped.
    pub fn list(&self) -> Vec<HistoryItem> {
        let Ok(entries) = std::fs::read_dir(&self.root) else {
            return Vec::new();
        };
        let mut items: Vec<HistoryItem> = entries
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .filter_map(|e| {
                let id = e.file_name().to_string_lossy().to_string();
                self.get(&id).ok()
            })
            .collect();
        items.sort_by(|a, b| b.created_at.cmp(&a.created_at).then_with(|| b.id.cmp(&a.id)));
        items
    }

    pub fn get(&self, id: &str) -> Result<HistoryItem> {
        let meta = self.path(id, HistoryFile::Meta)?;
        let bytes = std::fs::read(&meta).map_err(|_| HistoryError::NotFound(id.to_string()))?;
        Ok(serde_json::from_slice(&bytes)?)
    }

    /// Adds a new capture and prunes old items beyond the limit.
    pub fn add(&self, original_png: &[u8], thumb_png: &[u8], width: u32, height: u32, source: &str) -> Result<HistoryItem> {
        let now = Local::now();
        let base = now.format("%Y%m%d-%H%M%S-%3f").to_string();
        let mut id = base.clone();
        let mut n = 1;
        while self.root.join(&id).exists() {
            n += 1;
            id = format!("{base}-{n}");
        }
        let dir = self.root.join(&id);
        std::fs::create_dir_all(&dir)?;
        let item = HistoryItem {
            id: id.clone(),
            created_at: now,
            width,
            height,
            source: source.to_string(),
            revision: 1,
            edited: false,
            box_file_id: None,
            box_url: None,
            share_url: None,
            uploaded_revision: None,
            saved_path: None,
        };
        let result = (|| -> Result<()> {
            write_atomic(&dir.join(HistoryFile::Original.file_name()), original_png)?;
            write_atomic(&dir.join(HistoryFile::Thumb.file_name()), thumb_png)?;
            self.save_meta(&item)?;
            Ok(())
        })();
        if let Err(err) = result {
            let _ = std::fs::remove_dir_all(&dir);
            return Err(err);
        }
        self.prune()?;
        Ok(item)
    }

    /// Stores the edited image (and the editor document) for an item.
    pub fn update_image(
        &self,
        id: &str,
        image_png: &[u8],
        thumb_png: &[u8],
        width: u32,
        height: u32,
        annotations_json: Option<&str>,
    ) -> Result<HistoryItem> {
        let mut item = self.get(id)?;
        write_atomic(&self.path(id, HistoryFile::Image)?, image_png)?;
        write_atomic(&self.path(id, HistoryFile::Thumb)?, thumb_png)?;
        match annotations_json {
            Some(json) => write_atomic(&self.path(id, HistoryFile::Annotations)?, json.as_bytes())?,
            None => {
                let _ = std::fs::remove_file(self.path(id, HistoryFile::Annotations)?);
            }
        }
        item.width = width;
        item.height = height;
        item.edited = true;
        item.revision += 1;
        self.save_meta(&item)?;
        Ok(item)
    }

    pub fn annotations(&self, id: &str) -> Result<Option<String>> {
        let path = self.path(id, HistoryFile::Annotations)?;
        match std::fs::read_to_string(path) {
            Ok(s) => Ok(Some(s)),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(e) => Err(e.into()),
        }
    }

    pub fn save_meta(&self, item: &HistoryItem) -> Result<()> {
        let path = self.path(&item.id, HistoryFile::Meta)?;
        write_atomic(&path, &serde_json::to_vec_pretty(item)?)?;
        Ok(())
    }

    /// Read-modify-write of the metadata.
    pub fn modify(&self, id: &str, f: impl FnOnce(&mut HistoryItem)) -> Result<HistoryItem> {
        let mut item = self.get(id)?;
        f(&mut item);
        self.save_meta(&item)?;
        Ok(item)
    }

    pub fn delete(&self, id: &str) -> Result<()> {
        let dir = self.dir(id)?;
        if dir.exists() {
            std::fs::remove_dir_all(dir)?;
        }
        Ok(())
    }

    /// Deletes every item; returns how many there were.
    pub fn clear(&self) -> Result<usize> {
        let items = self.list();
        for item in &items {
            self.delete(&item.id)?;
        }
        Ok(items.len())
    }

    fn prune(&self) -> Result<()> {
        let limit = self.limit();
        for item in self.list().into_iter().skip(limit) {
            self.delete(&item.id)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn store(limit: usize) -> (tempfile::TempDir, HistoryStore) {
        let dir = tempfile::tempdir().unwrap();
        let store = HistoryStore::new(dir.path().join("history"), limit).unwrap();
        (dir, store)
    }

    #[test]
    fn keeps_only_last_n() {
        let (_dir, store) = store(10);
        let mut ids = Vec::new();
        for i in 0..13 {
            ids.push(store.add(b"png", b"thumb", 10 + i, 10, "region").unwrap().id);
        }
        let list = store.list();
        assert_eq!(list.len(), 10);
        // newest first, the three oldest are gone
        assert_eq!(list[0].id, ids[12]);
        assert_eq!(list[9].id, ids[3]);
        assert!(store.get(&ids[0]).is_err());
    }

    #[test]
    fn lowering_limit_prunes() {
        let (_dir, store) = store(10);
        for _ in 0..5 {
            store.add(b"png", b"thumb", 1, 1, "region").unwrap();
        }
        store.set_limit(2).unwrap();
        assert_eq!(store.list().len(), 2);
    }

    #[test]
    fn update_and_annotations() {
        let (_dir, store) = store(10);
        let item = store.add(b"orig", b"thumb", 100, 50, "region").unwrap();
        assert_eq!(store.current_image_path(&item.id).unwrap().file_name().unwrap(), "original.png");
        let updated = store
            .update_image(&item.id, b"edited", b"thumb2", 80, 40, Some(r#"{"shapes":[]}"#))
            .unwrap();
        assert!(updated.edited);
        assert_eq!(updated.revision, 2);
        assert_eq!((updated.width, updated.height), (80, 40));
        assert_eq!(store.current_image_path(&item.id).unwrap().file_name().unwrap(), "image.png");
        assert_eq!(store.annotations(&item.id).unwrap().as_deref(), Some(r#"{"shapes":[]}"#));
        // original stays untouched for re-editing
        assert_eq!(std::fs::read(store.path(&item.id, HistoryFile::Original).unwrap()).unwrap(), b"orig");

        let m = store
            .modify(&item.id, |i| i.share_url = Some("https://advant.one/x".into()))
            .unwrap();
        assert_eq!(store.get(&item.id).unwrap().share_url, m.share_url);
    }

    #[test]
    fn rejects_path_traversal() {
        let (_dir, store) = store(10);
        assert!(store.path("../secrets", HistoryFile::Meta).is_err());
        assert!(store.path("a/b", HistoryFile::Meta).is_err());
        assert!(store.path("", HistoryFile::Meta).is_err());
        assert!(store.get("..").is_err());
    }

    #[test]
    fn delete_and_clear() {
        let (_dir, store) = store(10);
        let a = store.add(b"1", b"t", 1, 1, "region").unwrap();
        store.add(b"2", b"t", 1, 1, "region").unwrap();
        store.delete(&a.id).unwrap();
        assert_eq!(store.list().len(), 1);
        assert_eq!(store.clear().unwrap(), 1);
        assert!(store.list().is_empty());
        assert_eq!(store.clear().unwrap(), 0);
    }
}
